#!/bin/bash

JOBNAME=$1
shift
JOBFILE=$1
shift

JOBCT=`wc -l $JOBFILE`

if [ ! -d "./out" ]; then
  mkdir out
fi

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname $SCRIPT`

echo qsub -N $JOBNAME -o out/ -j y -e out/  \
      -l h_vmem=8.0G -l h_rt=12:00:00 \
      -P gscid -l m_core=1 -q long \
      -V -cwd -t 1-${JOBCT} \
     ~/bin/runJobInArray $JOBFILE
qsub -N $JOBNAME -o out/ -j y -e out/  \
      -l h_vmem=8.0G -l h_rt=12:00:00 \
      -P gscid -l m_core=1 -q long \
      -V -cwd -t 1-${JOBCT} \
     ~/bin/runJobInArray $JOBFILE
