#!/bin/bash

JOBNAME=$1
shift

if [ ! -d "./out" ]; then
  mkdir out
fi

# -l h_rt=12:00:00

echo qsub -N $JOBNAME -j y -o out/ -e out/  \
      -l m_mem_free=8.0G -l m_core=4 \
      -q long -P gscid \
      -V -cwd -b y  \
     "$@"
qsub -N $JOBNAME -j y -o out/ -e out/  \
      -l m_mem_free=8.0G -l m_core=4 \
      -q long -P gscid \
      -V -cwd -b y  \
     "$@"
