#!/bin/bash

#NB GATK3.4 requires Java 1.8

LOCIFILE="NULL"
BAMSFILE="NULL"
PLOIDY=1
OUTFILE="GATK_out.vcf"
VARONLY="-out_mode EMIT_ALL_SITES"
MODE="DISCOVERY"
PICARD=/seq/software/picard/1.99/bin
GATK=/humgen/gsa-hpprojects/GATK/bin/GenomeAnalysisTK-3.4-0-g7e26428

while getopts "B:b:R:l:p:o:m:V" opt; do
  case $opt in
    b) BAM=${OPTARG} ;;
    B) BAMSFILE=$OPTARG ;;
#    l) LOCUS=$OPTARG ;;
    l) LOCIFILE=$OPTARG ;;
    p) PLOIDY=$OPTARG;;
    R) REF=$OPTARG;;
    o) OUTFILE=$OPTARG;;
    m) MODE=$OPTARG;;
    V) VARONLY="";;
   \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

#BAMSFILE must end in '.list'
if [[ $BAMSFILE!="NULL" ]]; 
  then 
  BAM=$BAMSFILE
fi

#check ref.dict file is present, otherwise create
if [ ! -f ${REF//fasta/dict} ]
  then
  java -jar ${PICARD}/CreateSequenceDictionary.jar R=${REF} O=${REF//fasta/dict}
fi

if [[ $LOCIFILE == *"bed" ]]
  then
  perl -lane 'print $F[0].":".$F[1]."-".$F[2]' $LOCIFILE > ${LOCIFILE//.bed/.intervals}
  LOCIFILE=${LOCIFILE//.bed/.intervals}
fi

java -jar  ${GATK}/GenomeAnalysisTK.jar \
    -T UnifiedGenotyper \
    -I ${BAM} \
    -ploidy ${PLOIDY} -glm GENERALPLOIDYSNP \
    -o ${OUTFILE} \
    -pnrm EXACT_GENERAL_PLOIDY \
    -R ${REF} \
    -L ${LOCIFILE} \
    -gt_mode $MODE  \
    ${VARONLY}
