#!/bin/bash

JOBNAME=$1
shift

if [ ! -d "./out" ]; then
  mkdir out
fi

echo bsub -J $JOBNAME -o out/${JOBNAME}.oe -e out/${JOBNAME}.oe \
     -R 'select[mem>8000] rusage[mem=8000]  span[ptile=4]' \
     -M 8000 -n 4 -q forest \
     "$@"
bsub -J $JOBNAME -o out/${JOBNAME}.oe -e out/${JOBNAME}.oe \
     -R 'select[mem>8000] rusage[mem=8000]  span[ptile=4]' \
     -M 8000 -n 4 -q forest \
     "$@"
